services:
  db:
    image: postgres:16-alpine
    container_name: busgo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: busgo_user
      POSTGRES_PASSWORD: superuser
      POSTGRES_DB: busgo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U busgo_user -d busgo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: busgo_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: