"""create seats table

Revision ID: 1ff01c90f5ab
Revises: 5c00013086f2
Create Date: 2026-08-14 17:29:49.247106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff01c90f5ab'
down_revision: Union[str, None] = '5c00013086f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('bus_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.String(length=20), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Enum('LEFT_WINDOW', 'LEFT_AISLE', 'RIGHT_AISLE', 'RIGHT_WINDOW', name='seatposition'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    # ### end Alembic commands ###
