"""booking table add in is_active

Revision ID: 3356822e9616
Revises: 7c2a1f4e8b90
Create Date: 2026-08-22 21:04:48.981280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3356822e9616'
down_revision: Union[str, None] = '7c2a1f4e8b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'is_active')
    # ### end Alembic commands ###
