"""bus table add in features

Revision ID: 37408449dae9
Revises: b8676019676a
Create Date: 2026-08-21 17:10:36.162898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37408449dae9'
down_revision: Union[str, None] = 'b8676019676a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buses', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buses', 'features')
    # ### end Alembic commands ###
