"""create TripSeats Table

Revision ID: 391438cc6c16
Revises: d1388eacf236
Create Date: 2026-08-18 12:31:52.508488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391438cc6c16'
down_revision: Union[str, None] = 'd1388eacf236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_seats',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'HELD', 'BOOKED', 'CANCELLED', name='trip_seat_status'), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booked_by', sa.UUID(), nullable=True),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('AVAILABLE', 'HELD', 'BOOKED', 'CANCELLED')", name='ck_trip_seat_status'),
    sa.ForeignKeyConstraint(['booked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'seat_id', name='uq_trip_seat')
    )
    op.create_index(op.f('ix_trip_seats_hold_expires_at'), 'trip_seats', ['hold_expires_at'], unique=False)
    op.create_index(op.f('ix_trip_seats_id'), 'trip_seats', ['id'], unique=False)
    op.create_index(op.f('ix_trip_seats_status'), 'trip_seats', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_seats_status'), table_name='trip_seats')
    op.drop_index(op.f('ix_trip_seats_id'), table_name='trip_seats')
    op.drop_index(op.f('ix_trip_seats_hold_expires_at'), table_name='trip_seats')
    op.drop_table('trip_seats')
    # ### end Alembic commands ###
