"""add user table in is_superuser field

Revision ID: 41508a23f8d3
Revises: 138e3d0b66b2
Create Date: 2026-08-12 14:08:18.452781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41508a23f8d3'
down_revision: Union[str, None] = '138e3d0b66b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', 
        sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
