"""create promotion table

Revision ID: 56bd83480696
Revises: 658fc6abfed2
Create Date: 2026-08-21 20:00:26.256036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56bd83480696'
down_revision: Union[str, None] = '658fc6abfed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Promotion name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Promotion description'),
    sa.Column('promo_code', sa.String(length=50), nullable=False, comment='Promotion code'),
    sa.Column('discount_percentage', sa.Float(), nullable=False, comment='Discount percentage for the promotion'),
    sa.Column('discount_amount', sa.Float(), nullable=True, comment='Discount amount for the promotion'),
    sa.Column('max_usage', sa.Integer(), nullable=False, comment='Maximum number of times the promotion can be used'),
    sa.Column('max_usage_per_user', sa.Integer(), nullable=False, comment='Maximum times a single user can use this promotion'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Promotion expiration date'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates if the promo is active'),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'DISABLED', name='promotionstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)
    op.create_index(op.f('ix_promotions_name'), 'promotions', ['name'], unique=False)
    op.create_index(op.f('ix_promotions_promo_code'), 'promotions', ['promo_code'], unique=True)
    op.create_table('promotion_usages',
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'CANCELLED', name='usagestatus'), nullable=False),
    sa.Column('discount_amount_applied', sa.Float(), nullable=False),
    sa.Column('promotion_id', sa.UUID(), nullable=False, comment='Promotion ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who used this promotion'),
    sa.Column('booking_id', sa.UUID(), nullable=True, comment='Booking ID (if applicable)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_usages_booking_id'), 'promotion_usages', ['booking_id'], unique=False)
    op.create_index(op.f('ix_promotion_usages_id'), 'promotion_usages', ['id'], unique=False)
    op.create_index(op.f('ix_promotion_usages_promotion_id'), 'promotion_usages', ['promotion_id'], unique=False)
    op.create_index(op.f('ix_promotion_usages_user_id'), 'promotion_usages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotion_usages_user_id'), table_name='promotion_usages')
    op.drop_index(op.f('ix_promotion_usages_promotion_id'), table_name='promotion_usages')
    op.drop_index(op.f('ix_promotion_usages_id'), table_name='promotion_usages')
    op.drop_index(op.f('ix_promotion_usages_booking_id'), table_name='promotion_usages')
    op.drop_table('promotion_usages')
    op.drop_index(op.f('ix_promotions_promo_code'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_name'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_id'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
