"""bus table add in image_url

Revision ID: 658fc6abfed2
Revises: 37408449dae9
Create Date: 2026-08-21 17:24:51.290460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658fc6abfed2'
down_revision: Union[str, None] = '37408449dae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buses', sa.Column('bus_image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buses', 'bus_image_url')
    # ### end Alembic commands ###
