"""add payment model in gatway_reponse

Revision ID: 953b4d6d05e7
Revises: f5801f4271a9
Create Date: 2026-08-18 18:11:46.955275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '953b4d6d05e7'
down_revision: Union[str, None] = 'f5801f4271a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('gateway_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'gateway_data')
    # ### end Alembic commands ###
