"""add travel_date to bookings

Revision ID: b8676019676a
Revises: e32f367b6b41
Create Date: 2026-08-19 17:24:35.342300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8676019676a'
down_revision: Union[str, None] = 'e32f367b6b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('travel_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'travel_date')
    # ### end Alembic commands ###
