"""create trip table

Revision ID: d1388eacf236
Revises: 9f2c4e8a1b3d
Create Date: 2026-08-15 19:13:53.832845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1388eacf236'
down_revision: Union[str, None] = '9f2c4e8a1b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('bus_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('local_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('foreigner_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('local_festival_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('foreigner_festival_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('booking_open_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booking_close_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('festival_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('festival_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED', name='trip_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('arrival_time > departure_time', name='ck_trips_arrival_after_departure'),
    sa.CheckConstraint('booking_close_date > booking_open_date', name='ck_trips_booking_close_after_open'),
    sa.CheckConstraint('foreigner_price >= 0', name='ck_trips_foreigner_price_non_negative'),
    sa.CheckConstraint('local_price >= 0', name='ck_trips_local_price_non_negative'),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_departure_time'), 'trips', ['departure_time'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_departure_time'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
