"""change trip_seat table

Revision ID: e32f367b6b41
Revises: 9a1b2c3d4e5f
Create Date: 2026-08-19 14:59:59.918674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32f367b6b41'
down_revision: Union[str, None] = '9a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_seats', sa.Column('travel_date', sa.Date(), nullable=False))
    op.drop_constraint('uq_trip_seat', 'trip_seats', type_='unique')
    op.create_index(op.f('ix_trip_seats_travel_date'), 'trip_seats', ['travel_date'], unique=False)
    op.create_unique_constraint('uq_trip_seat_date', 'trip_seats', ['trip_id', 'seat_id', 'travel_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_trip_seat_date', 'trip_seats', type_='unique')
    op.drop_index(op.f('ix_trip_seats_travel_date'), table_name='trip_seats')
    op.create_unique_constraint('uq_trip_seat', 'trip_seats', ['trip_id', 'seat_id'])
    op.drop_column('trip_seats', 'travel_date')
    # ### end Alembic commands ###
